---
title: "Homework 8"
format: 
  html:
    output-file: "index"
embed-resources: true
editor: 
  markdown: 
    wrap: 72
---

```{r}
library(altair)
library(reticulate)
library(tidyverse)
```

## Exercise 1 (Supply and demand)

### Stacked bar graph of capapcity and demand
```{r}
data <- read_csv("swd-lets-practice.csv") 

chart1 <- alt$Chart(data)$
  transform_fold(
    as.list(c("capacity", "demand")),
    as.list(c("variable", "value"))
  )$
  mark_bar()$
  encode(
    x = alt$X("date:T", title = "Date"),
    xOffset = "variable:N",
    y = alt$Y("value:Q", title = "Count"),
    color = alt$Color(
      "variable:N",
      scale = alt$Scale(
        domain = c("demand", "capacity"),
        range = c("lightblue", "orange")  
      )
    )
  )$
  properties(width = 500, height = 300)

chart1


```
### Line graph of demand and capacity
```{r}
chart2 <- alt$Chart(data)$
  transform_fold(
    as.list(c("capacity", "demand")),
    as.list(c("variable", "value"))
  )$
  mark_line()$
  encode(
    x = alt$X("date:T", title = "Date"),
    xOffset = "variable:N",
    y = alt$Y("value:Q", title = "Count"),
    color = alt$Color(
      "variable:N",
      scale = alt$Scale(
        domain = c("demand", "capacity"),
        range = c("lightblue", "orange")  
      )
    )
  )$
  properties(width = 500, height = 300)

chart2

```

### Stacked bar graph of barchart and unmet demand
```{r}
data <- read_csv("swd-lets-practice.csv") |>
  mutate(
    date = paste0(date, "-01"),
    capacity = as.numeric(str_replace_all(capacity, ",", "")),
    demand   = as.numeric(str_replace_all(demand, ",", ""))
  )
data2 <- data |>
  mutate(
    unmet = pmax(demand - capacity, 0)
  )

chart3 <- alt$Chart(data2)$
  transform_fold(
    as.list(c("capacity", "unmet")),
    as.list(c("variable", "value"))
  )$
  mark_bar()$
  encode(
    x = alt$X("date:T", title = "Date"),
    xOffset = "variable:N",                 
    y = alt$Y("value:Q", title = "Count"),
    color = alt$Color(
      "variable:N",
      scale = alt$Scale(
        domain = c("unmet", "capacity"),
        range = c("darkblue", "orange")
      )
    )
  )$
  properties(width = 500, height = 300)

chart3

```

### Dot map of demand and capacity
```{r}
chart4 <- alt$Chart(data)$
  transform_fold(
    as.list(c("capacity", "demand")),
    as.list(c("variable", "value"))
  )$
  mark_circle(size = 60)$
  encode(
    x = alt$X("date:T", title = "Date"),
    y = alt$Y("value:Q", title = "Count"),
    color = alt$Color(
      "variable:N",
      scale = alt$Scale(
        domain = c("demand", "capacity"),
        range = c("lightblue", "orange")
      )
    )
  )$
  properties(width = 500, height = 300)

chart4

```

### Line chart of unmet demand
```{r}
chart5 <- alt$Chart(data2)$
  mark_line()$
  encode(
    x = alt$X("date:T", title = "Date"),
    y = alt$Y("unmet:Q", title = "Unmet Demand"),
    color = alt$Color(
      value = "#d62728"
    )
  )$
  properties(width = 500, height = 300)

chart5

```
### Side by side bare graph of demand and capacity
```{r}
chart6 <- alt$Chart(data)$
  transform_fold(
    as.list(c("capacity", "demand")),
    as.list(c("variable", "value"))
  )$
  mark_bar()$
  encode(
    x = alt$X("date:O", title = "Date"),
    xOffset = "variable:N",
    y = alt$Y("value:Q", title = "Count"),
    color = alt$Color(
      "variable:N",
      scale = alt$Scale(
        domain = c("demand", "capacity"),
        range = c("lightblue", "orange")
      )
    )
  )$
properties(width = 500, height = 300)

chart6
```



## Exercise 2(Jobs)
```{r}
library(vegabrite)
jobs_url <- 
  "https://cdn.jsdelivr.net/npm/vega-datasets@2.8.0/data/jobs.json"


#| fig-cap: "This is a caption for the figure."
vl_chart() |>
  vl_mark_point() |>
  vl_pivot("year", groupby = list("job", "sex"), value = "perc") |>
  vl_encode_x("1850:Q") |>
  vl_scale_x(type = "symlog", constant = 0.00001) |>  # note: scale must be set quite small
  vl_encode_y("2000:Q") |>
  vl_scale_y(type = "symlog", constant = 0.00001) |>  # note: scale must be set quite small
  vl_facet_column("sex:N", title = "") |>
  vl_encode_tooltip_array(list("job", "sex", "1850", "2000")) |>
  vl_add_properties(
    title =  list( 
      text = "Percent of people working various jobs",
      subtitle = "Each dot represents the one occupation. Hover to see which occupation it is."
      )) |>
  vl_add_data_url(jobs_url) 
```


a.
```{python}
import altair as alt
import pandas as pd

jobs_url = "https://cdn.jsdelivr.net/npm/vega-datasets@2.8.0/data/jobs.json"
df = pd.read_json(jobs_url)

Perc = (
    df.groupby(["year", "sex"], as_index=False)["perc"]
      .sum()
)

chart = (
    alt.Chart(Perc)
    .mark_line(point=True)
    .encode(
        x=alt.X("year:O", title="Year"),
        y=alt.Y("perc:Q", title="Sum of perc"),
        color="sex:N"
    )
    .properties(
        title="Sum of perc by Year and Sex"
    )
)

chart

```



## Exercise 3
```{python}
df = pd.read_csv("gas_prices.csv")
data = "https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.csv"
country = pd.read_csv(data)
country.column

long = df.melt(
    id_vars="country",
    var_name="year",
    value_name="price_usd_per_gallon"
)

long = long.dropna(subset=["price_usd_per_gallon"])
long["year"] = long["year"].astype(int)

iso = country.rename(columns={
    "name": "iso_name",
    "alpha_3": "iso3"
})[["iso_name", "iso3", "region", "sub_region"]]



```


